version: "3.9"

services:
bot:
  build: .
  container_name: discordbotSD
  restart: unless-stopped
  env_file:
    - .env
  volumes:
    - ./img:/app/img
    - ./static:/app/static
    - ./resource:/app/resource
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"